import { format } from 'date-fns'
import type { Business, Appointment, Voucher, CheckIn, Receipt, Review } from '@/types/database'

const now = new Date().toISOString()

export const demoBusinesses: Business[] = [
  {
    id: 'demo-1',
    name: 'Fresh Cuts Barbershop',
    type: 'barbershop',
    address: '123 Market Street',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19104',
    phone: '(215) 555-0101',
    email: 'phillycuts@example.com',
    owner_id: 'demo-owner-1',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '10:00', close: '16:00' },
    },
  },
  {
    id: 'demo-2',
    name: 'Elite Styles Salon',
    type: 'salon',
    address: '456 Broad Street',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19106',
    phone: '(215) 555-0202',
    email: 'community@example.com',
    owner_id: 'demo-owner-2',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
    hours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '19:00' },
      saturday: { open: '09:00', close: '17:00' },
    },
  },
  {
    id: 'demo-legal',
    name: 'Community Legal Services',
    type: 'Legal',
    address: '1424 Chestnut St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19102',
    phone: '215-981-3700',
    owner_id: 'demo-owner-3',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-legal-2',
    name: 'Philly Defenders Association',
    type: 'Legal',
    address: '1441 Sansom St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19102',
    phone: '215-568-3190',
    owner_id: 'demo-owner-l2',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-legal-3',
    name: 'Temple Legal Aid Clinic',
    type: 'Legal',
    address: '1719 N Broad St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19122',
    phone: '215-204-1800',
    owner_id: 'demo-owner-l3',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-legal-4',
    name: 'Just Law Center',
    type: 'Legal',
    address: '1500 Walnut St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19102',
    phone: '215-555-0999',
    owner_id: 'demo-owner-l4',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-tech',
    name: 'Tech Impact Training',
    type: 'Education',
    address: '417 N 8th St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19123',
    phone: '215-555-0400',
    owner_id: 'demo-owner-4',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-edu-2',
    name: 'Year Up Greater Philadelphia',
    type: 'Education',
    address: '1835 Market St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19103',
    phone: '215-555-0800',
    owner_id: 'demo-owner-e2',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-edu-3',
    name: 'Community College of Philadelphia',
    type: 'Education',
    address: '1700 Spring Garden St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19130',
    phone: '215-751-8000',
    owner_id: 'demo-owner-e3',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-edu-4',
    name: 'Hopeworks Camden',
    type: 'Education',
    address: '808 Market St',
    city: 'Camden',
    state: 'NJ',
    zip: '08102',
    phone: '856-338-0707',
    owner_id: 'demo-owner-e4',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-health',
    name: 'Vybe Urgent Care',
    type: 'Health',
    address: '1500 Spring Garden St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19130',
    phone: '215-555-0500',
    owner_id: 'demo-owner-5',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-health-2',
    name: 'Mazzoni Center',
    type: 'Health',
    address: '1348 Bainbridge St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19147',
    phone: '215-563-0652',
    owner_id: 'demo-owner-h2',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-health-3',
    name: 'Jefferson Health Center',
    type: 'Health',
    address: '833 Chestnut St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19107',
    phone: '1-800-533-3669',
    owner_id: 'demo-owner-h3',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-health-4',
    name: 'Planned Parenthood - Center City',
    type: 'Health',
    address: '1144 Locust St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19107',
    phone: '215-351-5560',
    owner_id: 'demo-owner-h4',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-housing',
    name: 'Housing First Initiative',
    type: 'Housing',
    address: '2000 Hamilton St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19130',
    phone: '215-555-0600',
    owner_id: 'demo-owner-6',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-housing-2',
    name: 'Project HOME',
    type: 'Housing',
    address: '1515 Fairmount Ave',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19130',
    phone: '215-232-7272',
    owner_id: 'demo-owner-ho2',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-housing-3',
    name: 'Habitat for Humanity',
    type: 'Housing',
    address: '1829 N 19th St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19121',
    phone: '215-765-6000',
    owner_id: 'demo-owner-ho3',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-housing-4',
    name: 'Liberty Housing Options',
    type: 'Housing',
    address: '700 Race St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19106',
    phone: '215-555-9000',
    owner_id: 'demo-owner-ho4',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-empl',
    name: 'Second Chance Employment',
    type: 'Employment',
    address: '123 Broad St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19109',
    phone: '215-555-0300',
    owner_id: 'demo-owner-7',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-empl-2',
    name: 'PA CareerLink',
    type: 'Employment',
    address: '1617 JFK Blvd',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19103',
    phone: '215-557-2592',
    owner_id: 'demo-owner-em2',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-empl-3',
    name: 'Urban League of Philadelphia',
    type: 'Employment',
    address: '121 S Broad St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19107',
    phone: '215-985-3220',
    owner_id: 'demo-owner-em3',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-empl-4',
    name: 'Philly Youth Network',
    type: 'Employment',
    address: '400 Market St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19106',
    phone: '267-502-3800',
    owner_id: 'demo-owner-em4',
    created_at: now,
    updated_at: now,
    is_active: true,
    is_youth_friendly: true,
  },
]

export const demoAppointments: (Appointment & { business?: { name: string } })[] = [
  {
    id: 'demo-appt-1',
    business_id: 'demo-legal',
    business: { name: 'Community Legal Services' },
    scheduled_date: format(new Date(Date.now() + 86400000 * 5), 'yyyy-MM-dd'), // 5 days from now
    scheduled_time: '10:00',
    status: 'confirmed',
    service_type: 'Expungement Consultation',
    user_id: 'demo-user',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-appt-2',
    business_id: 'demo-1',
    business: { name: 'Fresh Cuts Barbershop' },
    scheduled_date: format(new Date(Date.now() + 86400000), 'yyyy-MM-dd'), // Tomorrow
    scheduled_time: '14:30',
    status: 'confirmed',
    service_type: 'Classic Cut',
    user_id: 'demo-user',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-appt-3',
    business_id: 'demo-health',
    business: { name: 'Vybe Urgent Care' },
    scheduled_date: format(new Date(Date.now() + 86400000 * 14), 'yyyy-MM-dd'), // 2 weeks
    scheduled_time: '09:15',
    status: 'confirmed',
    service_type: 'Annual Wellness Check',
    user_id: 'demo-user',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-appt-new-1',
    business_id: 'demo-edu-2',
    business: { name: 'Year Up Greater Philadelphia' },
    scheduled_date: format(new Date(Date.now() + 86400000 * 3), 'yyyy-MM-dd'), // 3 days from now
    scheduled_time: '11:00',
    status: 'confirmed',
    service_type: 'Enrollment Interview',
    user_id: 'demo-user',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-appt-new-2',
    business_id: 'demo-housing-2',
    business: { name: 'Project HOME' },
    scheduled_date: format(new Date(Date.now() + 86400000 * 7), 'yyyy-MM-dd'), // 7 days from now
    scheduled_time: '15:45',
    status: 'pending',
    service_type: 'Housing Application Review',
    user_id: 'demo-user',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-appt-new-3',
    business_id: 'demo-empl-2',
    business: { name: 'PA CareerLink' },
    scheduled_date: format(new Date(Date.now() + 86400000 * 4), 'yyyy-MM-dd'), // 4 days from now
    scheduled_time: '13:00',
    status: 'confirmed',
    service_type: 'Resume Workshop',
    user_id: 'demo-user',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-appt-4',
    business_id: 'demo-housing',
    business: { name: 'Housing First Initiative' },
    scheduled_date: format(new Date(Date.now() - 86400000 * 2), 'yyyy-MM-dd'), // 2 days ago
    scheduled_time: '11:00',
    status: 'completed',
    service_type: 'Application Intake',
    user_id: 'demo-user',
    created_at: now,
    updated_at: now,
  },
]

export const demoVouchers: (Voucher & { business?: { name: string } })[] = [
  {
    id: 'demo-v1',
    business_id: 'demo-tech', // Derived from name map
    amount: 500,
    created_at: now,
    updated_at: now,
    expires_at: new Date(Date.now() + 86400000 * 90).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v2',
    business_id: 'demo-legal',
    amount: 150,
    created_at: now,
    updated_at: now,
    expires_at: new Date(Date.now() + 86400000 * 60).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v-housing',
    business_id: 'demo-housing',
    business: { name: 'Housing First Initiative' },
    amount: 200,
    created_at: now,
    updated_at: now,
    expires_at: new Date(Date.now() + 86400000 * 30).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v-health',
    business_id: 'demo-health',
    amount: 50,
    created_at: now,
    updated_at: now,
    expires_at: new Date(Date.now() + 86400000 * 45).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v-empl',
    business_id: 'demo-empl',
    amount: 75,
    created_at: now,
    updated_at: now,
    expires_at: new Date(Date.now() + 86400000 * 60).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v3',
    business_id: 'demo-1',
    amount: 25,
    created_at: '2025-09-01T10:00:00Z',
    updated_at: now,
    expires_at: '2025-12-31T23:59:59Z',
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v4',
    business_id: 'demo-2',
    amount: 40,
    created_at: '2025-08-15T09:00:00Z',
    updated_at: now,
    expires_at: '2025-11-30T23:59:59Z',
    status: 'used',
    used_at: '2025-10-01T14:00:00Z',
    cohort_member_id: 'demo-user',
  },
]

export const demoCheckIns: CheckIn[] = [
  {
    id: 'demo-check-1',
    user_id: 'demo-user',
    type: 'requested',
    notes: 'Need help preparing for job interview next week.',
    requested_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-check-2',
    user_id: 'demo-user',
    type: 'completed',
    notes: 'Discussed housing paperwork.',
    requested_at: '2025-09-20T14:00:00Z',
    completed_at: '2025-09-21T15:00:00Z',
    created_at: '2025-09-20T14:00:00Z',
    updated_at: '2025-09-21T15:00:00Z',
  },
]

export const demoReceipts: Receipt[] = [
  {
    id: 'demo-r1',
    user_id: 'demo-user',
    merchant: 'Fresh Cuts',
    amount: 25,
    date: '2025-10-10',
    category: 'Grooming',
    status: 'processed',
    created_at: now,
    updated_at: now,
  },
]

export const demoReviews: Review[] = [
  {
    id: 'demo-review-1',
    business_id: 'demo-1',
    user_id: 'demo-user',
    rating: 5,
    text: 'Best fade I’ve had in years. Super friendly.',
    created_at: '2025-09-01T12:00:00Z',
  },
  {
    id: 'demo-review-2',
    user_id: 'demo-user',
    business_id: 'demo-2',
    rating: 4,
    text: 'Clean shop, quick service, loved the style.',
    created_at: '2025-09-05T15:00:00Z',
  },
]
