import { format } from 'date-fns'
import type { Business } from '@/types/database'

export const demoBusinesses: any[] = [
  {
    id: 'demo-1',
    name: 'Fresh Cuts Barbershop',
    type: 'barbershop',
    address: '123 Market Street',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19104',
    phone: '(215) 555-0101',
    email: 'phillycuts@example.com',
    is_active: true,
    is_youth_friendly: true,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '10:00', close: '16:00' },
    },
  },
  {
    id: 'demo-2',
    name: 'Elite Styles Salon',
    type: 'salon',
    address: '456 Broad Street',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19106',
    phone: '(215) 555-0202',
    email: 'community@example.com',
    is_active: true,
    is_youth_friendly: true,
    hours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '19:00' },
      saturday: { open: '09:00', close: '17:00' },
    },
  },
  {
    id: 'demo-legal',
    name: 'Community Legal Services',
    type: 'Legal',
    address: '1424 Chestnut St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19102',
    phone: '215-981-3700',
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-tech',
    name: 'Tech Impact Training',
    type: 'Education',
    address: '417 N 8th St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19123',
    phone: '215-555-0400',
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-health',
    name: 'Vybe Urgent Care',
    type: 'Health',
    address: '1500 Spring Garden St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19130',
    phone: '215-555-0500',
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-housing',
    name: 'Housing First Initiative',
    type: 'Housing',
    address: '2000 Hamilton St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19130',
    phone: '215-555-0600',
    is_active: true,
    is_youth_friendly: true,
  },
  {
    id: 'demo-empl',
    name: 'Second Chance Employment',
    type: 'Employment',
    address: '123 Broad St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19109',
    phone: '215-555-0300',
    is_active: true,
    is_youth_friendly: true,
  },
]

export const demoAppointments = [
  {
    id: 'demo-appt-1',
    business_id: 'demo-legal',
    business: { name: 'Community Legal Services' },
    scheduled_date: format(new Date(Date.now() + 86400000 * 5), 'yyyy-MM-dd'), // 5 days from now
    scheduled_time: '10:00',
    status: 'confirmed',
    service_type: 'Expungement Consultation',
    user_id: 'demo-user',
  },
  {
    id: 'demo-appt-2',
    business_id: 'demo-1',
    business: { name: 'Fresh Cuts Barbershop' },
    scheduled_date: format(new Date(Date.now() + 86400000), 'yyyy-MM-dd'), // Tomorrow
    scheduled_time: '14:30',
    status: 'confirmed',
    service_type: 'Classic Cut',
    user_id: 'demo-user',
  },
  {
    id: 'demo-appt-3',
    business_id: 'demo-health',
    business: { name: 'Vybe Urgent Care' },
    scheduled_date: format(new Date(Date.now() + 86400000 * 14), 'yyyy-MM-dd'), // 2 weeks
    scheduled_time: '09:15',
    status: 'confirmed',
    service_type: 'Annual Wellness Check',
    user_id: 'demo-user',
  },
  {
    id: 'demo-appt-4',
    business_id: 'demo-housing',
    business: { name: 'Housing First Initiative' },
    scheduled_date: format(new Date(Date.now() - 86400000 * 2), 'yyyy-MM-dd'), // 2 days ago
    scheduled_time: '11:00',
    status: 'completed',
    service_type: 'Application Intake',
    user_id: 'demo-user',
  },
]

export const demoVouchers = [
  {
    id: 'demo-v1',
    business: { name: 'Tech Impact Training' },
    amount: 500,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 86400000 * 90).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v2',
    business: { name: 'Community Legal Services' },
    amount: 150,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 86400000 * 60).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v-housing',
    business: { name: 'Housing First Initiative' },
    amount: 200,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 86400000 * 30).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v-health',
    business: { name: 'Vybe Urgent Care' },
    amount: 50,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 86400000 * 45).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v-empl',
    business: { name: 'Second Chance Employment' },
    amount: 75,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 86400000 * 60).toISOString(),
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v3',
    business: { name: 'Fresh Cuts Barbershop' },
    amount: 25,
    created_at: '2025-09-01T10:00:00Z',
    expires_at: '2025-12-31T23:59:59Z',
    status: 'active',
    cohort_member_id: 'demo-user',
  },
  {
    id: 'demo-v4',
    business: { name: 'Elite Styles Salon' },
    amount: 40,
    created_at: '2025-08-15T09:00:00Z',
    expires_at: '2025-11-30T23:59:59Z',
    status: 'used',
    used_at: '2025-10-01T14:00:00Z',
    cohort_member_id: 'demo-user',
  },
]

export const demoCheckIns = [
  {
    id: 'demo-check-1',
    type: 'requested',
    notes: 'Need help preparing for job interview next week.',
    requested_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-check-2',
    type: 'completed',
    notes: 'Discussed housing paperwork.',
    requested_at: '2025-09-20T14:00:00Z',
    completed_at: '2025-09-21T15:00:00Z',
    created_at: '2025-09-20T14:00:00Z',
  },
]

export const demoReceipts = [
  {
    id: 'demo-r1',
    merchant: 'Fresh Cuts',
    amount: 25,
    date: '2025-10-10',
    category: 'Grooming',
    status: 'processed',
    attachment: null,
  },
]

export const demoReviews = [
  {
    id: 'demo-review-1',
    business_id: 'demo-1',
    rating: 5,
    text: 'Best fade I’ve had in years. Super friendly.',
    created_at: '2025-09-01T12:00:00Z',
  },
  {
    id: 'demo-review-2',
    business_id: 'demo-2',
    rating: 4,
    text: 'Clean shop, quick service, loved the style.',
    created_at: '2025-09-05T15:00:00Z',
  },
]
